# Generated by Django 2.2.14 on 2020-08-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schedule',
            new_name='schedule1',
        ),
    ]
